name: Docker BuildX Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout source
        uses: actions/checkout@v2
      -
        name: Set Environment Variables
        run: |
          echo "VERSION=1.13.0" >> $GITHUB_ENV
          echo "PLATFORM=linux/amd64,linux/arm64" >> $GITHUB_ENV
          echo "DOCKERHUB_SLUG=$(echo ${{ secrets.DOCKERHUB_USERNAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.VERSION }}
          platforms: ${{ env.PLATFORM }}
          push: true
          tags: |
              ${{ env.DOCKERHUB_SLUG }}/unbound:latest